<?php
$names = array (
  'article' => '文章模板',
  'brand' => '品牌模板',
  'buy' => '求購模板',
  'chip' => '模板片斷',
  'city' => '城市分站',
  'company' => '公司模板',
  'down' => '下載模板',
  'exhibit' => '展會模板',
  'extend' => '功能擴展',
  'footer' => '全站頁腳',
  'group' => '團購模板',
  'header' => '全站頁頭',
  'homepage' => '公司主頁',
  'index' => '網站首頁',
  'info' => '信息模板',
  'job' => '人才模板',
  'know' => '知道模板',
  'mail' => '郵件模板',
  'mall' => '商城模板',
  'member' => '商務中心',
  'message' => '提示信息',
  'photo' => '圖庫模板',
  'quote' => '行情模板',
  'sell' => '供應模板',
  'special' => '專題模板',
  'tag' => '標籤模板',
  'video' => '視頻模板',
  'wap' => 'WAP',
);
?>