<?php
$names = array (
  'brand' => '品牌展示',
  'buy' => '採購清單',
  'contact' => '聯繫方式',
  'credit' => '誠信檔案',
  'footer' => '公共頁腳',
  'header' => '公共頁頭',
  'honor' => '榮譽資質',
  'index' => '公司首頁',
  'info' => '招商代理',
  'introduce' => '公司介紹',
  'job' => '人才招聘',
  'link' => '友情鏈接',
  'main_brand' => '首頁品牌展示',
  'main_elite' => '首頁產品推薦',
  'main_info' => '首頁招商代理',
  'main_introduce' => '首頁公司介紹',
  'main_photo' => '首頁公司相冊',
  'main_sell' => '首頁最新供應',
  'main_video' => '首頁公司視頻',
  'message' => '留言詢價',
  'news' => '公司新聞',
  'photo' => '公司相冊',
  'sell' => '供應產品',
  'side' => '側欄',
  'side_announce' => '側欄網站公告',
  'side_contact' => '側欄聯繫方式',
  'side_honor' => '側欄榮譽資質',
  'side_link' => '側欄友情鏈接',
  'side_news' => '側欄新聞中心',
  'side_page' => '側欄單頁',
  'side_search' => '側欄站內搜索',
  'side_type' => '側欄產品分類',
  'video' => '公司視頻',
);
?>