<?php
$names = array (
  'area' => '地區',
  'article' => '文章',
  'brand' => '品牌',
  'buy' => '求購',
  'category' => '分類',
  'charge' => '充值',
  'company' => '公司',
  'contact' => '聯繫內容',
  'content' => '信息內容',
  'exhibit' => '展會',
  'footer' => 'WAP頁腳',
  'group' => '團購',
  'header' => 'WAP頁頭',
  'index' => 'WAP首頁',
  'info' => '信息',
  'job' => '招聘',
  'know' => '知道',
  'login' => '登錄',
  'mall' => '商城',
  'message' => '站內信',
  'message_send' => '發送站內信',
  'msg' => '信息提示',
  'quote' => '報價',
  'resume' => '簡歷',
  'sell' => '供應',
);
?>