<?php
$names = array (
  'brand-column' => '品牌-成功故事',
  'brand-search-tool' => '品牌-搜索工具',
  'buy_type' => '求購類型', 
  'captcha' => '驗證碼',
  'catalog' => '行業分類',
  'catalog_accordion' => '分類伸縮',
  'catalog_list' => '分類列表',
  'comment' => '評論調用',
  'contact' => '聯繫方式收費',
  'content' => '內容收費',
  'detail-fav' => '內容收藏',
  'ebook-column' => '電子書排行',
  'exhibit-catalog' => '展會列表分類',
  'exhibit-column' => '近期展會',
  'google_translate' => '谷歌翻譯',
  'guest_contact' => '遊客聯繫方式',
  'letter' => '字母索引',
  'line' => '會員狀態',
  'mall_tip_tool' => '商城工具列',
  'password' => '密碼輸入',
  'player' => '視頻播放',
  'poll' => '行業票選',
  'property' => '分類屬性',
  'query_tool' => '展會月份查詢',
  'question' => '驗證問題',
  'sell-detail' => '銷售細節',
  'show_toolbar' => '社群工具列',
  'tip_tool' => '銷售工具列',
  'user' => '會員登錄',
  'video-column' => '視頻排行',
  'vote' => '投票調用',
  'zoom' => '圖片縮放',
);
?>